openapi: 3.0.0
info:
  title: express-ts-todo API
  description: express-ts-todoのAPI仕様書です。
  version: 0.1.0
  contact:
    name: Naoya Abe
    email: naoya3402@gmail.com
servers:
  - url: 'http://localhost:8080'
    description: Development server
  - url: 'https://stg.sample-server.com/v1'
    description: Staging server
  - url: 'https://api.sample-server.com/v1'
    description: Production server
paths:
tags:
  - name: todo
    description: todo関連のAPI
