openapi: 3.0.0
info:
  title: express-ts-todo API
  description: express-ts-todoのAPI仕様書です。
  version: 0.1.0
  contact:
    name: Naoya Abe
    email: naoya3402@gmail.com
servers:
  - url: 'http://localhost:8080'
    description: Development server
  - url: 'https://stg.sample-server.com/v1'
    description: Staging server
  - url: 'https://api.sample-server.com/v1'
    description: Production server
paths:
  /todo/list:
    get:
      summary: Your GET endpoint
      tags:
        - todo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
              examples:
                Example 1:
                  value:
                    - id: 1
                      title: ランニング
                      details: 毎朝6時に起きてランニングをする。
                      isDone: false
                    - id: 2
                      title: 英会話
                      details: 毎日就業後に英会話をする。
                      isDone: true
      operationId: get-todo-list
      description: Todo一覧の取得
    parameters: []
  '/todo/:todoId':
    get:
      summary: Your GET endpoint
      tags:
        - todo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
      operationId: get-todo
      description: パスパラメーターで指定されたidのTodoを取得
    parameters: []
  /todo:
    post:
      summary: ''
      operationId: post-todo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
              examples:
                Example 1:
                  value:
                    id: 1
                    title: ランニング
                    details: 毎朝6時に起きてランニングをする。
                    isDone: false
      tags:
        - todo
      description: 新規にTodoを作成
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                details:
                  type: string
              required:
                - title
            examples:
              Example 1:
                value:
                  title: ランニング
                  details: 毎朝6時に起きてランニングをする。
    patch:
      summary: ''
      operationId: patch-todo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
              examples:
                Example 1:
                  value:
                    id: 1
                    title: ランニング
                    details: 毎朝6時に起きてランニングをする。
                    isDone: false
      tags:
        - todo
      description: 指定されたidのTodoを編集
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                todoId:
                  type: integer
                title:
                  type: string
                details:
                  type: string
                isDone:
                  type: boolean
              required:
                - todoId
                - title
                - isDone
            examples:
              Example 1:
                value:
                  todoId: 1
                  title: ランニング
                  details: 毎朝6時に起きてランニングをする。
                  isDone: false
    delete:
      summary: ''
      operationId: delete-todo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
              examples:
                Example 1:
                  value:
                    id: 1
                    title: ランニング
                    details: 毎朝6時に起きてランニングをする。
                    isDone: false
      description: 指定されたidのTodoを削除
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                todoId:
                  type: integer
              required:
                - todoId
            examples:
              Example 1:
                value:
                  todoId: 1
      tags:
        - todo
    parameters: []
tags:
  - name: todo
    description: todo関連のAPI
components:
  schemas:
    Todo:
      title: Todo
      x-stoplight:
        id: sr3f67842zscf
      type: object
      x-examples:
        Example 1:
          id: 1
          title: ランニング
          details: 毎朝6時に起きてランニングをする。
          isDone: false
      properties:
        id:
          type: integer
        title:
          type: string
        details:
          type: string
        isDone:
          type: boolean
      required:
        - id
        - title
        - isDone
